### ISSUE TITLE
Missing .sql File

### ISSUE THREAD

**Issue by NiklasTerhorst** [michael-fa/GTA-City-Remake#1]
Nabend,

ich konnte im Projekt keine .sql Datei für den Datenbankimport finden. 
Kann eine angefügt werden oder steht das Projekt still?

**Comment by michael-fa** [comment]
Hallo,
Also das ganze Projekt ist eher eine Nachahmung an ein bekannteres älteres Gamemode, und kein eigenes Projekt. Die SQL kann ich bei Gelegenheit raussuchen, und sonst mach ich sie gerne fertig. Das Script hat jedoch keine Features die als abgeschlossen / fertig gelten. 
Würde mich dennoch freuen, wenn es genutzt wird und Stelle gerne meine Unterstützung zur Verfügung falls Interesse besteht. Die Datenbank kann dann im Laufe des Tages im Hauptverzeichnis des gesamten Codes hier auf GitHub gefunden werden.

**Comment by NiklasTerhorst** [comment]
Moin,
danke für die Info. Will das einfach bisschen weiter scripten.
